POST http://127.0.0.1:8080/aideData
Content-Type: application/json

{
  "img1": "img1",
  "img2": "img2",
  "motion": "true",
  "battery": "23",
  "key": "a243RDSFsdfsdko352"
}

###
POST http://127.0.0.1:8080/aideData
Content-Type: application/json

{
  "img1": "img1",
  "img2": "img2",
  "audio": "fsdgdfgdfg",
  "motion": "false",
  "battery": "88",
  "key": "fsdko352"
}

###
GET http://127.0.0.1:8080/aideData
Accept: application/json

###
GET http://127.0.0.1:8080/aideData/a243RDSFsdfsdko352
Accept: application/json

###
GET http://127.0.0.1:8080/aideData/difjgifdjgidfjgij
Accept: application/json

###
POST http://127.0.0.1:8080/aideData/delete/a243RDSFsdfsdko352
Accept: application/json

###
POST http://127.0.0.1:8080/aideData/delete/
Accept: application/json

###
GET http://127.0.0.1:8080/download/f039acad-ff93-434f-98aa-8.zip
Accept: application/zip